server:
  port: 8090
host:
  url: https://forecast9.p.rapidapi.com/rapidapi/forecast/
  forecastEndpoint : /summary/
  hourlyEndpoint : /hourly/
apiKeyAndValue:
  key: X-RapidAPI-Key
  value: dc606de45emsh81b758d10b60975p1126afjsna298dab2fd11
hostKeyAndValue:
  key: X-RapidAPI-Host
  value: forecast9.p.rapidapi.com
auth:
  id: client-id
  secret: client-secret





